[build]
  base = ""
  publish = "dist"
  command = "pip install -r requirements.txt && python setup.py sdist bdist_wheel"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
