[build]
  command = """
    python -m pip install --upgrade pip setuptools wheel &&
    pip install -e .[dev] &&
    python setup.py sdist bdist_wheel
  """
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11.11"
  PIP_NO_CACHE_DIR = "off"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
