[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && python setup.py build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
