[build]
  publish = "dist"
  command = "bash ./build.sh"

[build.environment]
  PYTHON_VERSION = "3.8.12"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
