[build]
  publish = "dist"
  command = "python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt && python setup.py sdist bdist_wheel"

[build.environment]
  PYTHON_VERSION = "3.8.0"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
