[build]
  publish = "dist"
  command = """
    mise use python@3.8 &&
    python -m pip install --upgrade pip setuptools wheel &&
    python -m pip install -r requirements.txt &&
    python setup.py sdist bdist_wheel
  """

[build.environment]
  PYTHON_VERSION = "3.8"
  MISE_PYTHON_COMPILE = "false"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
